//! The files the runtime writes for agents with only file access, and the small helpers
//! around them: a tool's own summary and a free id.

use sound_core::{
    AGENT_DOC_FILE, AGENT_DOCS_FOLDER, AgentDoc, Changes, Engine, EngineConfig, NO_PROBLEMS,
    PROBLEMS_FILE, Project, RegistryError,
};

use crate::tools::{
    BANK_RECORD, Dc, EXTENSION, Harness, SAMPLE_RATE, dc_record, id, level_record, registry,
};

#[test]
fn the_map_is_written_on_open_and_lists_the_docs_of_the_enabled_extensions() {
    let harness = Harness::new();
    let map = harness.read(AGENT_DOC_FILE);
    assert!(map.starts_with("<!-- Generated by the Sound Tools runtime"));
    assert_eq!(map, harness.project.agent_doc());
    // The form of every tool, and one line per doc that says when to open it.
    assert!(map.contains("| `test.bank` | `<name>/instance.json`, children next to it |"));
    assert!(map.contains("| `test.dc` | `<name>.json` |"));
    assert!(map.contains("| `agent-docs/project-json.md` | You change the tempo"));
    assert!(map.contains("| `agent-docs/test-tools.md` | You work on a test record. |"));
    assert!(!map.contains("{{"), "a placeholder is left: {map}");
    assert_eq!(harness.read("CLAUDE.md"), "@AGENTS.md\n");

    // The docs themselves, with the bar math of the project filled in.
    let doc = harness.read(&format!("{AGENT_DOCS_FOLDER}/test-tools.md"));
    assert!(doc.starts_with("<!-- Generated by the Sound Tools runtime"));
    assert!(doc.contains("# Test tools\n\nA bar is 3840 ticks in 4/4."));
    let project_json = harness.read(&format!("{AGENT_DOCS_FOLDER}/project-json.md"));
    assert!(project_json.contains(r#""extensions": ["test"],"#));
}

/// The runtime owns the markdown of the folder and nothing else in it.
#[test]
fn only_a_stale_doc_is_taken_out_of_the_docs_folder() {
    let harness = Harness::new();
    let folder = harness.path(AGENT_DOCS_FOLDER);
    std::fs::write(folder.join("recording.md"), "# Recording\n").unwrap();
    std::fs::write(folder.join("notes.txt"), "my notes").unwrap();
    std::fs::write(folder.join("take.wav"), [0_u8; 4]).unwrap();
    std::fs::create_dir(folder.join("mine")).unwrap();

    let harness = harness.reopen();
    assert!(!folder.join("recording.md").exists(), "a stale doc stays");
    for kept in ["notes.txt", "take.wav", "mine"] {
        assert!(folder.join(kept).exists(), "{kept} was taken away");
    }
    let doc = harness.read(&format!("{AGENT_DOCS_FOLDER}/test-tools.md"));
    assert!(doc.contains("# Test tools"), "the docs are written again");
}

#[test]
fn a_doc_name_that_is_not_a_file_name_is_refused() {
    let doc = |name| AgentDoc {
        name,
        when: "Never",
        markdown: "# No\n",
    };
    for name in ["../notes", "a/b", "notes.md", "Notes", "", "instance"] {
        let mut registry = registry();
        assert_eq!(
            registry.agent_doc(EXTENSION, doc(name)),
            Err(RegistryError::InvalidAgentDocName(name)),
            "{name:?}"
        );
        assert_eq!(
            registry.runtime_agent_doc(doc(name)),
            Err(RegistryError::InvalidAgentDocName(name)),
            "{name:?}"
        );
    }
}

/// The doc of `project.json` is in the list from the start, so it is taken like any other.
#[test]
fn a_second_doc_of_one_name_is_refused_whoever_registered_the_first() {
    let doc = |name| AgentDoc {
        name,
        when: "Never",
        markdown: "# No\n",
    };
    let mut registry = registry();
    for name in ["project-json", "test-tools"] {
        assert_eq!(
            registry.agent_doc(EXTENSION, doc(name)),
            Err(RegistryError::DuplicateAgentDoc(name)),
            "{name}"
        );
        assert_eq!(
            registry.runtime_agent_doc(doc(name)),
            Err(RegistryError::DuplicateAgentDoc(name)),
            "{name}"
        );
    }
    assert_eq!(registry.agent_doc(EXTENSION, doc("second")), Ok(()));
}

#[test]
fn the_map_is_not_written_again_while_its_text_is_the_same() {
    let harness = Harness::new();
    let modified = |harness: &Harness| {
        let metadata = std::fs::metadata(harness.path(AGENT_DOC_FILE)).unwrap();
        metadata.modified().unwrap()
    };
    let (before, text) = (modified(&harness), harness.read(AGENT_DOC_FILE));
    std::thread::sleep(std::time::Duration::from_millis(20));
    let harness = harness.reopen();
    assert_eq!(modified(&harness), before);
    assert_eq!(harness.read(AGENT_DOC_FILE), text);
}

#[test]
fn the_map_and_the_docs_follow_the_time_signature() {
    let mut harness = Harness::new();
    let project_file = harness.read("project.json").replace("4/4", "6/8");
    harness.write_and_apply("project.json", &project_file);
    harness.project.poll().unwrap();
    let map = harness.read(AGENT_DOC_FILE);
    assert!(map.contains("This project is in 6/8: a beat is 480 ticks and a bar is 2880 ticks."));
    assert!(map.contains("Bar 3, beat 2 is tick 6240."));
    let doc = harness.read(&format!("{AGENT_DOCS_FOLDER}/test-tools.md"));
    assert!(doc.contains("A bar is 2880 ticks in 6/8."));
}

#[test]
fn the_problems_file_is_there_while_the_project_is_open_and_gone_after_a_close() {
    let mut harness = Harness::new();
    assert_eq!(harness.read(PROBLEMS_FILE), NO_PROBLEMS);

    harness.write_and_apply("state/a.json", &dc_record(7.0));
    harness.write_and_apply("state/b.json", "{");
    harness.project.poll().unwrap();
    let problems = harness.read(PROBLEMS_FILE);
    let lines: Vec<&str> = problems.lines().collect();
    assert_eq!(lines.len(), 2);
    assert_eq!(
        lines[0],
        "state/a.json: state: value must be from -1 to 1, not 7"
    );
    assert!(lines[1].starts_with("state/b.json: "), "{problems}");

    harness.write_and_apply("state/a.json", &dc_record(0.5));
    harness.project.poll().unwrap();
    assert_eq!(harness.read(PROBLEMS_FILE).lines().count(), 1);
    std::fs::remove_file(harness.path("state/b.json")).unwrap();
    let removed = harness.path("state/b.json");
    harness.apply_outside_changes(&[removed]).unwrap();
    harness.project.poll().unwrap();
    assert_eq!(harness.read(PROBLEMS_FILE), NO_PROBLEMS);

    // A clean close removes it, so a missing file means that no runtime is watching.
    let Harness {
        project, folder, ..
    } = harness;
    drop(project);
    assert!(!folder.path().join(PROBLEMS_FILE).exists());
    assert!(folder.path().join(AGENT_DOC_FILE).exists());
}

#[test]
fn a_problems_file_that_a_crash_left_is_replaced_on_open() {
    let harness = Harness::new();
    std::fs::write(harness.path("state/a.json"), dc_record(7.0)).unwrap();
    let harness = harness.reopen();
    assert_eq!(harness.read(PROBLEMS_FILE).lines().count(), 1);
    // What a crash leaves: the file stays, and the record is fixed meanwhile.
    let stale = harness.read(PROBLEMS_FILE);
    let Harness {
        project, folder, ..
    } = harness;
    drop(project);
    std::fs::write(folder.path().join(PROBLEMS_FILE), stale).unwrap();
    std::fs::write(folder.path().join("state/a.json"), dc_record(0.5)).unwrap();
    let harness = Harness::open(folder);
    assert_eq!(harness.read(PROBLEMS_FILE), NO_PROBLEMS);
}

#[test]
fn a_read_only_project_writes_no_generated_files() {
    let harness = Harness::new();
    let Harness {
        project, folder, ..
    } = harness;
    drop(project);
    for file in [AGENT_DOC_FILE, "CLAUDE.md"] {
        std::fs::remove_file(folder.path().join(file)).unwrap();
    }
    let doc = format!("{AGENT_DOCS_FOLDER}/test-tools.md");
    std::fs::remove_file(folder.path().join(&doc)).unwrap();
    std::fs::write(folder.path().join("state/a.json"), dc_record(7.0)).unwrap();
    let (control, _engine) = Engine::new(EngineConfig::new(SAMPLE_RATE, 1));
    let mut project = Project::open_read_only(folder.path(), registry(), control).unwrap();
    project.poll().unwrap();
    assert_eq!(project.problems().len(), 1);
    for file in [AGENT_DOC_FILE, "CLAUDE.md", PROBLEMS_FILE, &doc] {
        assert!(!folder.path().join(file).exists(), "{file}");
    }

    // And it takes nothing away when it closes: the file of a live runtime next to it stays.
    std::fs::write(folder.path().join(PROBLEMS_FILE), NO_PROBLEMS).unwrap();
    drop(project);
    assert!(folder.path().join(PROBLEMS_FILE).exists());
}

#[test]
fn a_tool_summarises_itself_and_what_it_owns() {
    let mut harness = Harness::new();
    harness.write_and_apply("state/bank/instance.json", BANK_RECORD);
    for name in ["a", "b", "c"] {
        harness.write_and_apply(&format!("state/bank/{name}.json"), &level_record(0.1));
    }
    harness.write_and_apply("state/plain.json", &dc_record(0.5));
    assert_eq!(
        harness.project.summary(&id("bank")).as_deref(),
        Some("bank bank with 3 levels")
    );
    assert_eq!(harness.project.summary(&id("plain")), None);
    assert_eq!(harness.project.summary(&id("missing")), None);
    assert_eq!(harness.project.tool_of(&id("bank/a")), Some("test.level"));
}

#[test]
fn a_free_id_steps_over_live_instances_and_over_files_that_are_not_loaded() {
    let mut harness = Harness::new();
    assert_eq!(harness.project.free_id(&id("tone")).unwrap(), id("tone"));
    let mut changes = Changes::new();
    changes.create(id("tone"), Dc { value: 0.5 });
    harness.project.commit("Add", changes).unwrap();
    // `tone-2` is a file that does not load, `tone-3` a folder without a record.
    harness.write_and_apply("state/tone-2.json", "{");
    harness.write("state/tone-3/child.json", &dc_record(0.1));
    assert_eq!(harness.project.free_id(&id("tone")).unwrap(), id("tone-4"));
}
