//! Files the runtime writes into the project folder for agents that have only file access.
//!
//! `AGENTS.md` is the map. It holds what an agent needs on every task and lists the docs,
//! one line each saying when to open it. The docs themselves are one file per extension or
//! task under `agent-docs/`, so an agent reads the map and then only what its task needs.
//! `CLAUDE.md` imports the map, so Codex and Claude Code both find it. `problems.txt` lists
//! what [`Project::problems`] holds. It is there the whole time a runtime has the project
//! open, with one plain line when there are no problems, and it goes away when the project
//! closes. So an agent can tell "all is well" from "nobody is watching". Every file is
//! written only when its text changes.

use std::collections::BTreeMap;

use super::registry::AgentDoc;
use super::{Project, ProjectError};

pub const AGENT_DOC_FILE: &str = "AGENTS.md";
/// The folder of the docs the map points at.
pub const AGENT_DOCS_FOLDER: &str = "agent-docs";
pub const PROBLEMS_FILE: &str = "problems.txt";
const CLAUDE_FILE: &str = "CLAUDE.md";
const CLAUDE_TEXT: &str = "@AGENTS.md\n";
/// The whole of `problems.txt` when every file is live.
pub const NO_PROBLEMS: &str = "No problems. Every file is live.\n";
const MAP: &str = include_str!("agent_doc.md");
const GENERATED_NOTE: &str = "<!-- Generated by the Sound Tools runtime when the project opens. Do not edit: your changes are written over. -->\n\n";

/// `project.json` is core, not an extension, so the core brings its doc itself.
const PROJECT_FILE_DOC: AgentDoc = AgentDoc {
    name: "project-json",
    when: "You change the tempo or the time signature, or connect instances by hand",
    markdown: include_str!("project_json.md"),
};

impl Project {
    /// The text of `AGENTS.md` for this project: the map.
    ///
    /// These placeholders are filled in here and in every doc, so the bar math of every
    /// example follows the time signature of the project: `{{time_signature}}`,
    /// `{{ticks_per_beat}}`, `{{ticks_per_bar}}`, `{{bar_5_start}}`, `{{four_bars}}`,
    /// `{{bar_9_start}}` and `{{bar_3_beat_2}}`.
    pub fn agent_doc(&self) -> String {
        let mut tools = String::from("| Tool | Form |\n| --- | --- |\n");
        for (tool, extension, owns_children) in self.registry.tools() {
            if self.enables(extension) {
                let form = if owns_children {
                    "`<name>/instance.json`, children next to it"
                } else {
                    "`<name>.json`"
                };
                tools.push_str(&format!("| `{tool}` | {form} |\n"));
            }
        }

        let mut docs = String::from("| Doc | Read it when |\n| --- | --- |\n");
        for doc in self.agent_docs() {
            let (name, when) = (doc.name, doc.when);
            docs.push_str(&format!("| `{AGENT_DOCS_FOLDER}/{name}.md` | {when}. |\n"));
        }

        let map = MAP
            .replace("{{tools}}", tools.trim_end())
            .replace("{{docs}}", docs.trim_end());
        self.fill(&map)
    }

    /// Every doc this project writes under `agent-docs/`, in the order of the map.
    pub fn agent_docs(&self) -> impl Iterator<Item = AgentDoc> {
        let registered = self.registry.agent_docs(&self.project_file.extensions);
        std::iter::once(PROJECT_FILE_DOC).chain(registered)
    }

    /// The text of one doc, with the generated note in front of it.
    pub fn agent_doc_text(&self, doc: &AgentDoc) -> String {
        format!("{GENERATED_NOTE}{}", self.fill(doc.markdown.trim_end()))
    }

    fn enables(&self, extension: &str) -> bool {
        (self.project_file.extensions.iter()).any(|enabled| enabled == extension)
    }

    /// Fills the placeholders of the project in a generated text.
    fn fill(&self, text: &str) -> String {
        let time_signature = self.project_file.tempo_map.time_signature();
        let (beat, bar) = (
            time_signature.ticks_per_beat(),
            time_signature.ticks_per_bar(),
        );
        let extensions: Vec<String> = (self.project_file.extensions.iter())
            .map(|name| format!("{name:?}"))
            .collect();
        let values = [
            ("{{extensions}}", extensions.join(", ")),
            ("{{time_signature}}", time_signature.to_string()),
            ("{{ticks_per_beat}}", beat.to_string()),
            ("{{ticks_per_bar}}", bar.to_string()),
            ("{{bar_5_start}}", (4 * bar).to_string()),
            ("{{four_bars}}", (4 * bar).to_string()),
            ("{{bar_9_start}}", (8 * bar).to_string()),
            ("{{bar_3_beat_2}}", (2 * bar + beat).to_string()),
        ];
        let mut text = text.to_string();
        for (placeholder, value) in values {
            text = text.replace(placeholder, &value);
        }
        text
    }

    /// Brings the generated files up to date. Called when the project opens and from `poll`.
    /// A read-only project writes nothing.
    pub(crate) fn write_generated_files(&mut self) -> Result<(), ProjectError> {
        if self.read_only || !self.generated_are_stale {
            return Ok(());
        }
        // Before the writes: a failed write is reported once, not again on every poll.
        self.generated_are_stale = false;

        let mut problems = String::new();
        for problem in self.problems() {
            problems.push_str(&format!("{}: {}\n", problem.path, problem.message));
        }
        let problems = if problems.is_empty() {
            NO_PROBLEMS
        } else {
            &problems
        };
        self.storage
            .write_generated(PROBLEMS_FILE, Some(problems))?;
        self.storage
            .write_generated(AGENT_DOC_FILE, Some(&self.agent_doc()))?;
        self.storage
            .write_generated(CLAUDE_FILE, Some(CLAUDE_TEXT))?;
        let docs: BTreeMap<String, String> = self
            .agent_docs()
            .map(|doc| (format!("{}.md", doc.name), self.agent_doc_text(&doc)))
            .collect();
        self.storage
            .write_generated_folder(AGENT_DOCS_FOLDER, docs)?;
        Ok(())
    }
}

/// A clean close takes `problems.txt` away, so its absence means that no runtime watches.
impl Drop for Project {
    fn drop(&mut self) {
        if self.read_only {
            return;
        }
        // There is nobody left to report a failure to. A file that stays is what a crash
        // leaves too, and the agent doc says that such a file can be stale.
        match self.storage.write_generated(PROBLEMS_FILE, None) {
            Ok(()) | Err(_) => {}
        }
    }
}
