//! The generated agent docs: `AGENTS.md` is a map that lists them, every doc is written and
//! stable, and every example in any of them is a real record, in the bytes the runtime itself
//! would write. So the docs cannot rot.

use sound_core::{
    AGENT_DOC_FILE, AGENT_DOCS_FOLDER, ASSETS_FOLDER, Changes, InstanceId, Tempo, TempoMap,
    TimeSignatures,
};

use crate::support::{Harness, write};

/// The fenced `json` blocks of a markdown text, as (what follows `json` on the fence, body).
fn json_examples(markdown: &str) -> Vec<(String, String)> {
    let mut examples = Vec::new();
    let mut lines = markdown.lines();
    while let Some(line) = lines.next() {
        if let Some(label) = line.strip_prefix("```json") {
            let body: Vec<&str> = lines.by_ref().take_while(|line| *line != "```").collect();
            examples.push((label.trim().to_string(), body.join("\n") + "\n"));
        }
    }
    examples
}

/// The map and every doc it lists, as (path in the project folder, text).
fn map_and_docs(harness: &Harness) -> Vec<(String, String)> {
    let mut files = vec![AGENT_DOC_FILE.to_string()];
    for doc in harness.project.agent_docs() {
        files.push(format!("{AGENT_DOCS_FOLDER}/{}.md", doc.name));
    }
    let read = |path: &String| std::fs::read_to_string(harness.path(path)).unwrap();
    files
        .iter()
        .map(|path| (path.clone(), read(path)))
        .collect()
}

#[test]
fn the_map_lists_every_doc_and_all_of_them_are_written_and_stable_on_reopen() {
    let harness = Harness::new();
    let map = std::fs::read_to_string(harness.path(AGENT_DOC_FILE)).unwrap();
    let headings: Vec<&str> = map.lines().filter(|line| line.starts_with("## ")).collect();
    assert_eq!(
        headings,
        [
            "## Docs",
            "## Layout",
            "## Time",
            "## Rules",
            "## Check your work"
        ]
    );

    // One doc per extension and one for the runtime, each listed in the map with its line.
    let files = map_and_docs(&harness);
    let paths: Vec<&str> = files.iter().map(|(path, _)| path.as_str()).collect();
    assert_eq!(
        paths,
        [
            "AGENTS.md",
            "agent-docs/project-json.md",
            "agent-docs/arrangement.md",
            "agent-docs/audio.md",
            "agent-docs/compressor.md",
            "agent-docs/delay.md",
            "agent-docs/drums.md",
            "agent-docs/eq.md",
            "agent-docs/filter.md",
            "agent-docs/fit-tempo.md",
            "agent-docs/instrument.md",
            "agent-docs/limiter.md",
            "agent-docs/modulation.md",
            "agent-docs/plugins.md",
            "agent-docs/reverb.md",
            "agent-docs/sampler.md",
            "agent-docs/sfz.md",
            "agent-docs/library.md",
            "agent-docs/saturator.md",
            "agent-docs/tone.md",
            "agent-docs/utility.md",
            "agent-docs/wavetable.md",
            "agent-docs/inspect.md",
            "agent-docs/takes.md",
        ]
    );
    for (path, text) in &files {
        assert!(
            map.contains(&format!("| `{path}` |")) || path == AGENT_DOC_FILE,
            "{path}"
        );
        assert!(
            text.starts_with("<!-- Generated by the Sound Tools runtime"),
            "{path}"
        );
        assert!(!text.contains("{{"), "a placeholder is left in {path}");
        // Nothing of this machine is in them, so a project in git gets no diff from being
        // opened by another build or on another machine.
        let root = harness.project.root().display().to_string();
        let executable = std::env::current_exe().unwrap();
        for machine_specific in [
            root.as_str(),
            executable.to_str().unwrap(),
            "/Users/",
            "/tmp/",
        ] {
            assert!(
                !text.contains(machine_specific),
                "{machine_specific} in {path}"
            );
        }
    }
    let inspect = files.iter().find(|(path, _)| path.ends_with("/inspect.md"));
    let inspect = &inspect.unwrap().1;
    assert!(inspect.contains("```sh\nsound-tools . --inspect\nsound-tools . --render <wav>\n```"));
    assert_eq!(
        std::fs::read_to_string(harness.path("CLAUDE.md")).unwrap(),
        "@AGENTS.md\n"
    );

    // Written only when the text changes: reopening moves no modification time.
    let modified = |harness: &Harness| -> Vec<std::time::SystemTime> {
        let times = map_and_docs(harness).into_iter();
        times
            .map(|(path, _)| {
                let metadata = std::fs::metadata(harness.path(&path)).unwrap();
                metadata.modified().unwrap()
            })
            .collect()
    };
    let before = modified(&harness);
    std::thread::sleep(std::time::Duration::from_millis(20));
    let harness = harness.reopen();
    assert_eq!(modified(&harness), before);
    assert_eq!(map_and_docs(&harness), files);
}

#[test]
fn a_doc_that_the_project_no_longer_has_is_taken_out_of_the_folder() {
    let harness = Harness::new();
    let stale = harness.path(&format!("{AGENT_DOCS_FOLDER}/recording.md"));
    std::fs::write(&stale, "# Recording\n").unwrap();
    // Opening writes the docs again, and the folder then holds only them.
    let harness = harness.reopen();
    assert!(!stale.exists());
    assert!(
        harness
            .path(&format!("{AGENT_DOCS_FOLDER}/arrangement.md"))
            .exists()
    );
}

#[test]
fn every_json_example_of_the_map_and_the_docs_is_a_record_as_the_runtime_writes_it() {
    // The docs do not depend on the time signatures. A project whose time signature changes
    // is the harder case for the examples written into it.
    let mut harness = Harness::new();
    let time_signatures: TimeSignatures = serde_json::from_str(
        r#"[{"signature": "6/8", "bars": 3}, {"signature": "7/4", "bars": 1}]"#,
    )
    .unwrap();
    let mut changes = Changes::new();
    changes.set_tempo_map(TempoMap::constant(time_signatures, Tempo::default()));
    harness
        .project
        .commit("Set time signature", changes)
        .unwrap();
    harness.project.poll().unwrap();
    let all: Vec<(String, String)> = map_and_docs(&harness)
        .iter()
        .flat_map(|(_, text)| json_examples(text))
        .collect();
    assert_eq!(all.len(), 48);

    // The raw take of a recording is not a record: it is an asset the runtime writes once
    // and never reads back. Its example is checked as the file it is.
    let (assets, examples): (Vec<_>, Vec<_>) = all
        .into_iter()
        .partition(|(path, _)| path.starts_with("assets/"));
    assert_eq!(assets.len(), 1);
    for (path, body) in &assets {
        let raw: sound_notes::RawTake = serde_json::from_str(body).unwrap();
        // The bytes are those the runtime writes, so an agent reads the real thing.
        assert_eq!(&raw.json().unwrap(), body, "{path}");
        // A take lives under its own name, which no clip id decides.
        let folder = format!("{ASSETS_FOLDER}/{}/", sound_notes::TAKES_FOLDER);
        let name = path
            .strip_prefix(&folder)
            .and_then(|it| it.strip_suffix(".json"));
        let name = name.unwrap_or_else(|| panic!("{path} is not a take file"));
        assert!(sound_notes::Clip::is_valid_take_name(name), "{name}");
    }

    // They are written into an empty folder and are a project that loads whole.
    let folder = tempfile::tempdir().unwrap();
    for (path, body) in &examples {
        assert!(
            !path.is_empty(),
            "an example does not name its file: {body}"
        );
        write(folder.path(), path, body);
    }
    // The files the audio clip of its doc, the Sampler of its doc and the sample pad of
    // the drums play, which an agent copies in before it writes the record. Five seconds,
    // as the clip plays up to 4.5 s of it.
    for name in ["voice-take-1.wav", "kalimba.wav", "shaker.wav"] {
        let audio = folder.path().join("assets/audio").join(name);
        std::fs::create_dir_all(audio.parent().unwrap()).unwrap();
        let spec = hound::WavSpec {
            channels: 1,
            sample_rate: 48_000,
            bits_per_sample: 16,
            sample_format: hound::SampleFormat::Int,
        };
        let mut writer = hound::WavWriter::create(&audio, spec).unwrap();
        for _ in 0..5 * 48_000 {
            writer.write_sample(0_i16).unwrap();
        }
        writer.finalize().unwrap();
    }
    // The SFZ instrument of the Sampler doc: its file plays the kalimba.
    let sfz = folder
        .path()
        .join("assets/instruments/cello/cello-sustain.sfz");
    std::fs::create_dir_all(sfz.parent().unwrap()).unwrap();
    std::fs::write(&sfz, "<region> sample=../../audio/kalimba.wav").unwrap();
    let mut copy = Harness::open(folder);
    // The plugin doc names a plugin no machine is expected to have. That is the case its
    // doc describes: the record loads, the track is silent and the problem names the id.
    let problems: Vec<String> = copy
        .project
        .problems()
        .into_iter()
        .map(|problem| format!("{}: {}", problem.path, problem.message))
        .collect();
    // Every plugin the docs name is one no machine is expected to have: two instruments,
    // one per format, and the effect of the arrangement doc. The library instrument of the
    // library doc is not on this machine either: the test has no library.
    let expected = [
        "state/arrangement/piano/warmth.json: this machine has no CLAP plugin with the id \"com.example.warmth\"",
        "state/arrangement/rhodes/instrument.json: this machine has no CLAP plugin with the id \"com.example.piano\"",
        "state/arrangement/strings/instrument.json: this machine has no VST 3 plugin",
        "state/arrangement/violins/instrument.json: Violin section, sustain cannot play",
    ];
    assert_eq!(problems.len(), 4, "{problems:?}");
    for (problem, expected) in problems.iter().zip(expected) {
        assert!(problem.starts_with(expected), "{problems:?}");
    }
    let instances: Vec<String> = copy
        .project
        .instances()
        .map(|(id, _)| id.to_string())
        .collect();
    assert_eq!(
        instances,
        [
            "arrangement",
            "arrangement/bass",
            "arrangement/bass/dark",
            "arrangement/beat",
            "arrangement/beat/groove",
            "arrangement/beat/instrument",
            "arrangement/cello",
            "arrangement/cello/instrument",
            "arrangement/drums",
            "arrangement/drums/glue",
            "arrangement/guitar",
            "arrangement/guitar/swirl",
            "arrangement/kalimba",
            "arrangement/kalimba/instrument",
            "arrangement/keys",
            "arrangement/keys/room",
            "arrangement/lead",
            "arrangement/lead/echo",
            "arrangement/lead/slide",
            "arrangement/loops",
            "arrangement/loops/peaks",
            "arrangement/organ",
            "arrangement/organ/heat",
            "arrangement/pad",
            "arrangement/pad/narrow",
            "arrangement/piano",
            "arrangement/piano/instrument",
            "arrangement/piano/intro",
            "arrangement/piano/warmth",
            "arrangement/rhodes",
            "arrangement/rhodes/instrument",
            "arrangement/riser",
            "arrangement/riser/dark",
            "arrangement/strings",
            "arrangement/strings/instrument",
            "arrangement/synth",
            "arrangement/synth/instrument",
            "arrangement/violins",
            "arrangement/violins/instrument",
            "arrangement/vocal",
            "arrangement/vocal/clear",
            "arrangement/voice",
            "arrangement/voice/verse-take",
            "drone",
            "fit-tempo",
        ]
    );

    // The runtime writes every file again: delete all, undo, and a tempo edit with its
    // undo. The bytes are those of the examples, so an agent that copies their layout
    // makes no whitespace diff.
    let mut changes = Changes::new();
    changes.delete(&InstanceId::new("arrangement").unwrap());
    changes.delete(&InstanceId::new("drone").unwrap());
    let time_signatures = copy.project.project_file().tempo_map.time_signatures();
    changes.set_tempo_map(TempoMap::constant(
        time_signatures.clone(),
        Tempo::from_bpm(90.0).unwrap(),
    ));
    copy.project.commit("Delete all", changes).unwrap();
    assert!(
        !copy
            .path("state/arrangement")
            .join("instance.json")
            .exists()
    );
    copy.project.undo().unwrap();
    // A file two examples write, as the drum kit of the drums doc, holds the last.
    let last: std::collections::BTreeMap<&String, &String> =
        examples.iter().map(|(path, body)| (path, body)).collect();
    for (path, body) in last {
        let written = std::fs::read_to_string(copy.path(path)).unwrap();
        assert_eq!(&written, body, "{path}");
    }
}

/// The map is what an agent reads on every task. One doc more adds one line to it, not a
/// section: the whole agent doc was 2030 words before the split, the map was about 960. Each
/// built-in effect adds a line of about 20 words: with the Filter, the EQ, the Reverb and the
/// Compressor it is about 1130, with the doc of audio about 1150, with the Sampler about 1170,
/// with the Drum pad about 1200, with the Saturator about 1230, with the Limiter about 1255,
/// with the Utility about 1280, with the Modulation about 1300, with the Delay about 1320,
/// with the Wavetable about 1340, with the doc of SFZ files about 1350, and with the library
/// about 1365.
#[test]
fn the_map_stays_short() {
    let harness = Harness::new();
    let map = std::fs::read_to_string(harness.path(AGENT_DOC_FILE)).unwrap();
    let words = map.split_whitespace().count();
    assert!(words < 1375, "the map has {words} words");
}
