//! The generated agent docs: `AGENTS.md` is a map that lists them, every doc is written and
//! stable, and every example in any of them is a real record, in the bytes the runtime itself
//! would write. So the docs cannot rot.

use sound_core::{
    AGENT_DOC_FILE, AGENT_DOCS_FOLDER, Changes, InstanceId, Tempo, TempoMap, TimeSignature,
};

use crate::support::{Harness, write};

/// The fenced `json` blocks of a markdown text, as (what follows `json` on the fence, body).
fn json_examples(markdown: &str) -> Vec<(String, String)> {
    let mut examples = Vec::new();
    let mut lines = markdown.lines();
    while let Some(line) = lines.next() {
        if let Some(label) = line.strip_prefix("```json") {
            let body: Vec<&str> = lines.by_ref().take_while(|line| *line != "```").collect();
            examples.push((label.trim().to_string(), body.join("\n") + "\n"));
        }
    }
    examples
}

/// The map and every doc it lists, as (path in the project folder, text).
fn map_and_docs(harness: &Harness) -> Vec<(String, String)> {
    let mut files = vec![AGENT_DOC_FILE.to_string()];
    for doc in harness.project.agent_docs() {
        files.push(format!("{AGENT_DOCS_FOLDER}/{}.md", doc.name));
    }
    let read = |path: &String| std::fs::read_to_string(harness.path(path)).unwrap();
    files
        .iter()
        .map(|path| (path.clone(), read(path)))
        .collect()
}

#[test]
fn the_map_lists_every_doc_and_all_of_them_are_written_and_stable_on_reopen() {
    let harness = Harness::new();
    let map = std::fs::read_to_string(harness.path(AGENT_DOC_FILE)).unwrap();
    let headings: Vec<&str> = map.lines().filter(|line| line.starts_with("## ")).collect();
    assert_eq!(
        headings,
        [
            "## Docs",
            "## Layout",
            "## Time",
            "## Rules",
            "## Check your work"
        ]
    );

    // One doc per extension and one for the runtime, each listed in the map with its line.
    let files = map_and_docs(&harness);
    let paths: Vec<&str> = files.iter().map(|(path, _)| path.as_str()).collect();
    assert_eq!(
        paths,
        [
            "AGENTS.md",
            "agent-docs/project-json.md",
            "agent-docs/arrangement.md",
            "agent-docs/eq.md",
            "agent-docs/filter.md",
            "agent-docs/fit-tempo.md",
            "agent-docs/instrument.md",
            "agent-docs/plugins.md",
            "agent-docs/reverb.md",
            "agent-docs/tone.md",
            "agent-docs/inspect.md",
            "agent-docs/takes.md",
        ]
    );
    for (path, text) in &files {
        assert!(
            map.contains(&format!("| `{path}` |")) || path == AGENT_DOC_FILE,
            "{path}"
        );
        assert!(
            text.starts_with("<!-- Generated by the Sound Tools runtime"),
            "{path}"
        );
        assert!(!text.contains("{{"), "a placeholder is left in {path}");
        // Nothing of this machine is in them, so a project in git gets no diff from being
        // opened by another build or on another machine.
        let root = harness.project.root().display().to_string();
        let executable = std::env::current_exe().unwrap();
        for machine_specific in [
            root.as_str(),
            executable.to_str().unwrap(),
            "/Users/",
            "/tmp/",
        ] {
            assert!(
                !text.contains(machine_specific),
                "{machine_specific} in {path}"
            );
        }
    }
    let inspect = &files[10].1;
    assert!(inspect.contains("```sh\nruntime . --inspect\n```"));
    assert_eq!(
        std::fs::read_to_string(harness.path("CLAUDE.md")).unwrap(),
        "@AGENTS.md\n"
    );

    // Written only when the text changes: reopening moves no modification time.
    let modified = |harness: &Harness| -> Vec<std::time::SystemTime> {
        let times = map_and_docs(harness).into_iter();
        times
            .map(|(path, _)| {
                let metadata = std::fs::metadata(harness.path(&path)).unwrap();
                metadata.modified().unwrap()
            })
            .collect()
    };
    let before = modified(&harness);
    std::thread::sleep(std::time::Duration::from_millis(20));
    let harness = harness.reopen();
    assert_eq!(modified(&harness), before);
    assert_eq!(map_and_docs(&harness), files);
}

#[test]
fn a_doc_that_the_project_no_longer_has_is_taken_out_of_the_folder() {
    let harness = Harness::new();
    let stale = harness.path(&format!("{AGENT_DOCS_FOLDER}/recording.md"));
    std::fs::write(&stale, "# Recording\n").unwrap();
    // Opening writes the docs again, and the folder then holds only them.
    let harness = harness.reopen();
    assert!(!stale.exists());
    assert!(
        harness
            .path(&format!("{AGENT_DOCS_FOLDER}/arrangement.md"))
            .exists()
    );
}

#[test]
fn every_json_example_of_the_map_and_the_docs_is_a_record_as_the_runtime_writes_it() {
    for time_signature in ["4/4", "6/8", "7/4"] {
        // The docs of a project in this time signature.
        let mut harness = Harness::new();
        let signature: TimeSignature = time_signature.parse().unwrap();
        let mut changes = Changes::new();
        changes.set_tempo_map(TempoMap::constant(signature, Tempo::default()));
        harness
            .project
            .commit("Set time signature", changes)
            .unwrap();
        harness.project.poll().unwrap();
        let all: Vec<(String, String)> = map_and_docs(&harness)
            .iter()
            .flat_map(|(_, text)| json_examples(text))
            .collect();
        assert_eq!(all.len(), 21, "{time_signature}");

        // The raw take of a recording is not a record: it is an asset the runtime writes once
        // and never reads back. Its example is checked as the file it is.
        let (assets, examples): (Vec<_>, Vec<_>) = all
            .into_iter()
            .partition(|(path, _)| path.starts_with("assets/"));
        assert_eq!(assets.len(), 1, "{time_signature}");
        for (path, body) in &assets {
            let raw: sound_notes::RawTake = serde_json::from_str(body).unwrap();
            // The bytes are those the runtime writes, so an agent reads the real thing.
            assert_eq!(&raw.json(), body, "{path}");
            // A take lives under its own name, which no clip id decides.
            let folder = format!("{}/", sound_notes::TAKES_FOLDER);
            let name = path
                .strip_prefix(&folder)
                .and_then(|it| it.strip_suffix(".json"));
            let name = name.unwrap_or_else(|| panic!("{path} is not a take file"));
            assert!(sound_notes::Clip::is_valid_take_name(name), "{name}");
        }

        // They are written into an empty folder and are a project that loads whole.
        let folder = tempfile::tempdir().unwrap();
        for (path, body) in &examples {
            assert!(
                !path.is_empty(),
                "an example does not name its file: {body}"
            );
            write(folder.path(), path, body);
        }
        let mut copy = Harness::open(folder);
        // The plugin doc names a plugin no machine is expected to have. That is the case its
        // doc describes: the record loads, the track is silent and the problem names the id.
        let problems: Vec<String> = copy
            .project
            .problems()
            .into_iter()
            .map(|problem| format!("{}: {}", problem.path, problem.message))
            .collect();
        // Every plugin the docs name is one no machine is expected to have: two instruments,
        // one per format, and the effect of the arrangement doc.
        let expected = [
            "state/arrangement/piano/warmth.json: this machine has no CLAP plugin with the id \"com.example.warmth\"",
            "state/arrangement/rhodes/instrument.json: this machine has no CLAP plugin with the id \"com.example.piano\"",
            "state/arrangement/strings/instrument.json: this machine has no VST 3 plugin",
        ];
        assert_eq!(problems.len(), 3, "{time_signature}: {problems:?}");
        for (problem, expected) in problems.iter().zip(expected) {
            assert!(problem.starts_with(expected), "{problems:?}");
        }
        // The piano is written twice, the second time silenced with `"-inf"` and its warmth
        // bypassed, and that is what loaded.
        let piano = copy
            .project
            .resolve::<arrangement::TrackState>(
                &sound_core::InstanceId::new("arrangement/piano").unwrap(),
            )
            .unwrap();
        let piano = copy.project.state(&piano).unwrap();
        assert_eq!(piano.gain_db, f32::NEG_INFINITY);
        assert_eq!(piano.bypassed("warmth"), Some(true));
        let instances: Vec<String> = copy
            .project
            .instances()
            .map(|(id, _)| id.to_string())
            .collect();
        assert_eq!(
            instances,
            [
                "arrangement",
                "arrangement/bass",
                "arrangement/bass/dark",
                "arrangement/keys",
                "arrangement/keys/room",
                "arrangement/piano",
                "arrangement/piano/chords-bars-5-8",
                "arrangement/piano/instrument",
                "arrangement/piano/take-1",
                "arrangement/piano/warmth",
                "arrangement/rhodes",
                "arrangement/rhodes/instrument",
                "arrangement/strings",
                "arrangement/strings/instrument",
                "arrangement/vocal",
                "arrangement/vocal/clear",
                "drone",
                "fit-tempo",
            ]
        );

        // The runtime writes every file again: delete all, undo, and a tempo edit with its
        // undo. The bytes are those of the examples, so an agent that copies their layout
        // makes no whitespace diff.
        let mut changes = Changes::new();
        changes.delete(&InstanceId::new("arrangement").unwrap());
        changes.delete(&InstanceId::new("drone").unwrap());
        changes.set_tempo_map(TempoMap::constant(
            signature,
            Tempo::from_bpm(90.0).unwrap(),
        ));
        copy.project.commit("Delete all", changes).unwrap();
        assert!(
            !copy
                .path("state/arrangement")
                .join("instance.json")
                .exists()
        );
        copy.project.undo().unwrap();
        // A file two examples write, as the piano with its warmth bypassed, holds the last.
        let last: std::collections::BTreeMap<&String, &String> =
            examples.iter().map(|(path, body)| (path, body)).collect();
        for (path, body) in last {
            let written = std::fs::read_to_string(copy.path(path)).unwrap();
            assert_eq!(&written, body, "{path} in {time_signature}");
        }
    }
}

/// The map is what an agent reads on every task. One doc more adds one line to it, not a
/// section: the whole agent doc was 2030 words before the split, the map was about 960. Each
/// built-in effect adds a line of about 20 words: with the Filter, the EQ and the Reverb it is
/// 1115, and the bound leaves room for the Compressor.
#[test]
fn the_map_stays_short() {
    let harness = Harness::new();
    let map = std::fs::read_to_string(harness.path(AGENT_DOC_FILE)).unwrap();
    let words = map.split_whitespace().count();
    assert!(words < 1150, "the map has {words} words");
}
